services:
  httpd:
    build:
      context: ./docker
      dockerfile: customize-httpd.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docs/:/usr/local/apache2/htdocs/
